### ISSUE TITLE
Missing `content` for forename?

### ISSUE THREAD

**Issue by stefanomunarini** [relaton/relaton-data-ids#6]
It looks like `forename` is missing `content`. The grammar [here](https://github.com/relaton/relaton-models/blob/64718de5b6858cbd07f617dd7365bb972d84c453/models/Forename.lutaml#L5) defines this attribute as non-optional.

Example:
https://github.com/ietf-tools/relaton-data-rfcs/blob/3ea0704ed99564710389de2e35a745248e405a8b/data/RFC4037.yaml#L26C9-L31C21

Can you have a look at this @andrew2net ? Thanks

**Comment by stefano-tech-ai** [comment]
I think this was an oversight from my side. I will have a new look at this tomorrow. Will close it for now.

**Comment by andrew2net** [comment]
You are right, the `forename/content` is mandatory, but sometimes we have only initials without forename. @opoudjis and I have discussed this problem some time ago. Nick insisted that the `forename/content` should be mandatory but empty. In XML output it needs to have an empty `content` element, but YAML parses an empty content as `nil`:
```ruby
hash = YAML.load 'content:'
=> {"content"=>nil}

hash["content"]
=> nil
```
Without content Hash returns `nil` too:
```ruby
hash = {}
=> {}

hash["content"]
=> nil
```
So it doesn't make sense having empty `content` elements in the YAML output.

**Comment by stefano-tech-ai** [comment]
I get that on one hand it does not make sense to have empty content in the YAML. However, as relaton-py implements the Relaton model following the grammar described in the link in the post above, it fails when parsing data with missing content. 

This issue is blocking new IDs (and I think some RFCs too) to be indexed in the bibxml-service.

I also remember that this discussion has already taken place, even multiple times. Wouldn't it be better to just stick with the grammar, even if on a theoretical level it does not make too much sense, so that issues like this stops from happening (and these types of discussions too)? @andrew2net

**Comment by andrew2net** [comment]
@stefanomunarini fixed in relaton-bib v1.16.3. It will take time until all repositories will be updated. But I don't know if gems versions locked or not in the ietf-tools repos. If gems versions looked consider to update them.

**Comment by stefano-tech-ai** [comment]
Thanks @andrew2net ! I have upgraded the relaton-bib Gem in the bibxml-service Gemfile (https://github.com/ietf-ribose/bibxml-service/commit/068b48b44af3d45894f31ff2b87c19119bb60505). 

Is this the only Gem that needs to be upgraded? Thanks

**Comment by andrew2net** [comment]
@stefanomunarini all the relaton gems should have same minor version (it wasn't true for 14 and 15 minor versions but for 16 it's true). The minor version was 14 and now it is 16, so to be able work together all relaton gems should have minor version 16. The `~>1.16.3` notation means that major and minor versions are fixed but the bug version can be 3 or higher. You need to set `~>1.16.0` version for all the other relaton gems.

**Comment by stefano-tech-ai** [comment]
> @stefanomunarini all the relaton gems should have same minor version (it wasn't true for 14 and 15 minor versions but for 16 it's true). The minor version was 14 and now it is 16, so to be able work together all relaton gems should have minor version 16. The `~>1.16.3` notation means that major and minor versions are fixed but the bug version can be 3 or higher. You need to set `~>1.16.0` version for all the other relaton gems.

Thanks you @andrew2net . Shall `relaton` version be set to 1.16.1 (as for [latest release](https://github.com/relaton/relaton/releases/tag/v1.16.1))? Can you please review https://github.com/ietf-tools/bibxml-service/pull/379 ? Thank you

**Comment by andrew2net** [comment]
@stefanomunarini Ruby bundle install the latest bug fix release automatically, so it doesn't need to set latest version in Gemfile. 
The current Gemfile is good, but we start new minor versions with a zero bug fix number, for example `1.17.0`. With `~> 1.17.1` constrain in Gemfile version `1.17.0` won't be resolved.

**Comment by andrew2net** [comment]
@stefanomunarini can we close this issue?

**Comment by stefano-tech-ai** [comment]
Yes thank you very much @andrew2net

**Comment by stefano-tech-ai** [comment]
Hi @andrew2net just one more question. How can we propagate this update to ietf-tool/relaton-data-ids repo? Thanks

**Comment by andrew2net** [comment]
Hi @stefanomunarini, as I see relaton-data-ids uses a Gemfile from [ietf-tools/bibxml-service](https://github.com/ietf-ribose/relaton-data-ids/blob/db87c57d95da73764e7dbd3d750e34c146ab7032/.github/workflows/crawler.yml#L17). I think if we change the [Gemfile](https://raw.githubusercontent.com/ietf-tools/bibxml-service/main/Gemfile) it will propagate the update to all the repos that use the Gemfile. Please ask @strogonoff for more details.
